import express from 'express';
import { auth } from '../middleware/auth';
import { register } from '../controllers/register';
import { login, verifyCode, sendCode } from '../controllers/authController';
import { changePassword } from '../controllers/changepassword';
import { resetPassword } from '../controllers/resetPassword';
import { sendResetCode } from '../controllers/sendCode';
import { suspendUser } from '../controllers/suspendUser';
import { deleteUser } from '../controllers/deleteUser';
const router = express.Router();

router.post('/login', login);
router.post('/register', register);
router.post('/send-code', sendCode);
router.post('/verify-code', verifyCode);
router.post('/change-password', auth, changePassword);
router.post('/reset-password', resetPassword);
router.patch('/suspend/:id', suspendUser);
router.delete('/delete/:id', deleteUser);
export default router;
